#!/usr/bin/bash

  check_number_of_args() {
  if [ $must_n != $n_inParams ]
	then echo -e "Error!\nMust be $must_n parameters"
 	exit 1
  fi
}

  check_absolute_way() {
  if [ ! -d $abs_way ]
	  then echo "Wrong absolute way!"
	  exit 1
  fi
}

  check_args() {
  check_number_of_args $n_inParams
  check_absolute_way
}

