#!/usr/bin/bash

#nginx log in combined format:
#$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_    agent"
#Ex: 192.168.25.96 - - [20/Mar/2023:12:14:54 +0300] "GET /report.html HTTP/1.1" 200 112438 "-" "Mozilla/5.0     (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 YaBrowser/23.1.2.996 (beta) Yo    wser/2.5 Safari/537.36"
 

createStringForLog()
{	
	echo -n "$(createAddr) -"
	echo -n "$(createRemoteUser)"
	echo -n "$(createTime)"
	echo -n "$(createRequest)"
	echo -n "$(createStatus)"
	echo -n "$(createSendedBytes)"
	echo -n "$(createHttpReferer)"
	echo -n "$(createUserAgent)"
}

createAddr()
{
#	local ret=$((RANDOM % 10))
#	local i=0
#	for i in {1..3}
#	do
#		ret+="."$((RANDOM % 10))
#	done

	local ret="185.202"
	local i=0
	for i in {2..3}
	do
		ret+="."$((RANDOM % 100 + 1))
	done
	echo $ret
}

createRemoteUser()
{
	echo " -"
}

addZero()
{
	local ret=$1
	if [ ${#1} -lt 2 ]
		then ret=0$ret
	fi
	echo $ret
}

createTime()
{
	hhLog=$(addZero $hhLog)
	mmLog=$(addZero $mmLog)
	ssLog=$(addZero $ssLog)
	local getDDMMYY=$(date '+%d/%b/%Y' -d "$i day ago")
	echo " [$getDDMMYY:$hhLog:$mmLog:$ssLog $(date +%z)]"
}

createRequest()
{
	local ret="$(createMethod) $(createURI) $(createHTPP)"
	echo " \"$ret\""
}

createMethod()
{
	local ret=(GET POST PUT PATCH DELETE)
	local i=$((RANDOM % 5))
	echo "${ret[$i]}"
}

createURI()
{
	local ret=/$(shuf -n1 topGoogleRequest | awk -F '\t' '{print$2}')
	ret=$( echo ${ret// /%20} )
	#пробел в nginx_log заменяется на %20
	echo $ret
}

createHTPP()
{
	local ret=(HTPP/1.0 HTPP/1.1 HTPP/2)
	local i=$(($RANDOM % 3))
	echo "${ret[$i]}"
}

createStatus()
{
	local ret=(200 201 400 401 403 404 500 501 502 503)
	local i=$((RANDOM % 10))
	echo " ${ret[$i]}"
}

createSendedBytes()
{
	local min=197
	local max=1048576
	while true
	do
		local ret=$RANDOM
		if [[ ret -ge $min && ret -le $max ]] ; then
			break 1
		fi						
	done
	echo " $ret"
}

createUserAgent()
{
        local ret=$(cat ./userAgents | shuf -n1)
        echo " \"$ret\""
}

createHttpReferer()
{
	local ret="-"
	echo " \"$ret\""
}


# 200(OK) - успешно выполнен.
# 201(Create) - сервер выполнил запрос и создал новый ресурс.
# 400(Bad request) - клиент отправил неверный запрос
# 401(Unauthorized) - неверная авторизация либо ауентификация от клиента
# 403(Forbidden) - запрос ресурса от клиента на который нет прав для просмотра
# 404(Not found) - запрашиваемая страница не найдена
# 500(Iternal server error) - внутренняя проблема сервера
# 501(Not implemented) - метод запроса не поддерживается сервером
# 502(Bad gateway) - nginx сервер обработал запрос, передал его web-серверу, а тот не смог его обработать
# 503(Service unavailable) - ресурс временно недоступен

#Mozilla:
 #Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:47.0) Gecko/20100101 Firefox/47.0
 #Mozilla/5.0 (Macintosh; Intel Mac OS X x.y; rv:42.0) Gecko/20100101 Firefox/42.0
 
#Google Chrome:
 #Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103     Safari/537.36

#Opera:
 #Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106     Safari/537.36 OPR/38.0.2220.41
 
#Safari
 #Mozilla/5.0 (iPhone; CPU iPhone OS 13_5_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like     Gecko) Version/13.1.1 Mobile/15E148 Safari/604.1
 
#Internet Explorer
 #Mozilla/5.0 (compatible; MSIE 9.0; Windows Phone OS 7.5; Trident/5.0; IEMobile/9.0)
 
#Microsoft Edge
 #Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.    0.4472.124 Safari/537.36 Edg/91.0.864.59
 
#crowler and bot:
 #Mozilla/5.0 (compatible; YandexAccessibilityBot/3.0; +http://yandex.com/bots)

#Library and net tools:
 #curl/7.64.1

