#!/bib/bash

ft_cpu()
{
	echo $(top -b -n 1 | awk 'NR>7 {cpu=cpu+$9} END {printf("%.1f", cpu)}')
}

ft_mem()
{
	echo $(free -m | awk 'NR==2 {printf("%.1f", $3/$2*100)}')
}

ft_memTotal()
{
        echo $(top -b -n 1 | awk 'NR==4 {printf("%.1f", $4)}')
}


ft_diskUsed()
{
	echo $(df -m / | awk 'NR==2 {print $5}' | awk -F '%' '{printf "%0.1f", $1}')
}

ft_diskAvailable()
{
	echo $(df -m / | awk 'NR==2 {print $4}')
}
