#!/bin/bash

clearByDate()
{   
    DATE="$(date +%Y)-$(date +%m)-$(date +%d) $(date +%R)"
    echo  "Enter startDate and time (format:$DATE)"
    read  startDate

    echo "finishDate and time:" 
    read  finishDate

    #буду запускать поиск из /; из других директорий ищет только в них, а не во всей файловой системе
    cd /  
     sudo find . -type d -newerct "$startDate" ! -newerct "$finishDate" 2>/dev/null | grep "_[0-9][0-9][0-9][0-9][0-9][0-9]$" | xargs sudo rm -rf 2>/dev/null
}
